import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
async function rawSql() {
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),1, 'Banco do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),3, 'Banco da Amazônia S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),4, 'Banco do Nordeste do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),7, 'Banco Nacional de Desenvolvimento Econômico e Social 1') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),12, 'Banco Inbursa S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),17, 'BNY Mellon Banco S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),18, 'Banco Tricury S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),21, 'Banestes S.A. Banco do Estado do Espírito Santo') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),24, 'Banco Bandepe S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),25, 'Banco Alfa S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),29, 'Banco Itaú Consignado S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),33, 'Banco Santander (Brasil) S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),36, 'Banco Bradesco BBI S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),37, 'Banco do Estado do Pará S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),40, 'Banco Cargill S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),41, 'Banco do Estado do Rio Grande do Sul S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),47, 'Banco do Estado de Sergipe S.A. 2') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),63, 'Banco Bradescard S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),65, 'Banco Andbank (Brasil) S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),66, 'Banco Morgan Stanley S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),69, 'Banco Crefisa S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),70, 'BRB - Banco de Brasília S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),74, 'Banco J. Safra S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),75, 'Banco ABN AMRO S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),76, 'Banco 3  KDB do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),77, 'Banco Inter S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),79, 'Banco Original do Agronegócio S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),80, 'B&T Corretora de Câmbio Ltda.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),81, 'BancoSeguro S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),82, 'Banco Topázio S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),83, 'Banco da China Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),88, 'Banco Randon S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),92, 'BRK S.A. Crédito') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),94, 'Banco Finaxis S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),96, 'Banco B3 S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),104, 'Caixa Econômica Federal') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),107, 'Banco BOCOM BBM S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),114, 'Central Cooperativa de Crédito no Estado do Espírito Santo - Cecoop 4') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),117, 'Advanced Corretora de Câmbio Ltda') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),119, 'Banco Western Union do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),120, 'Banco Rodobens S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),121, 'Banco Agibank S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),122, 'Banco Bradesco BERJ S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),124, 'Banco Woori Bank do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),126, 'BR Partners Banco de Investimento S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),127, 'Codepe Corretora de Valores e Câmbio S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),130, 'Caruana S.A. - Sociedade de Crédito') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),133, 'Banco Cresol - Confederação Nacional das Cooperativas Centrais de Crédito e Economia Familiar e Solidária') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),134, 'BGC Liquidez Distribuidora de Títulos e Valores Mobiliários Ltda') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),142, 'Broker Brasil Corretora de Câmbio Ltda.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),144, 'Bexs Banco de Câmbio S/A') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),159, 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),163, 'Commerzbank Brasil S.A. - Banco Múltiplo') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),169, 'Banco Olé 6  Consignado S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),173, 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),180, 'CM Capital Markets Corretora de Câmbio, Títulos e Valores Mobiliários Ltda') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),184, 'Banco Itaú BBA S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),188, 'Ativa Investimentos S.A. Corretora de Títulos, Câmbio e Valores') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),208, 'Banco BTG Pactual S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),212, 'Banco Original S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),213, 'Banco Arbi S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),217, 'Banco John Deere S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),218, 'Banco BS2 S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),222, 'Banco 7  Crédit Agricole Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),224, 'Banco Fibra S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),233, 'Banco Cetelem S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),237, 'Banco Bradesco S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),241, 'Banco Clássico S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),243, 'Banco Máxima S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),246, 'Banco ABC Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),249, 'Banco Investcred Unibanco S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),250, 'BCV - Banco de Crédito e Varejo S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),253, 'Bexs Corretora de Câmbio S/A 8') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),265, 'Banco Fator S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),266, 'Banco Cédula S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),268, 'Bari Companhia Hipotecária') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),269, 'Banco HSBC S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),272, 'AGK Corretora de Cambio S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),280, 'Avista S.A. Crédito') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),288, 'Carol Distribuidora de Titulos e Valores Mobiliarios Ltda.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),292, 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),300, 'Banco de la Nacion Argentina') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),301, 'BPP Instituição de Pagamento S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),309, 'Cambionet Corretora de Câmbio Ltda.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),313, 'Amazônia Corretora de Câmbio Ltda.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),318, 'Banco BMG S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),320, 'China Construction Bank (Brasil) Banco Múltiplo S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),324, 'Cartos Sociedade de Crédito Direto S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),330, 'Banco Bari de Investimentos e Financiamentos S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),332, 'Acesso Soluções de Pagamento 9  S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),335, 'Banco Digio S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),336, 'Banco C6 S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),348, 'Banco XP S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),349, 'AL5 S.A. Crédito') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),362, 'Cielo S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),366, 'Banco Societe Generale Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),368, 'Banco CSF S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),370, 'Banco Mizuho do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),376, 'Banco J.P. Morgan S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),378, 'BBC Leasing S.A. - Arrendamento Mercantil') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),381, 'Banco Mercedes-Benz do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),387, 'Banco Toyota do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),389, 'Banco Mercantil do Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),390, 'Banco GM S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),393, 'Banco Volkswagen S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),394, 'Banco Bradesco Financiamentos S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),408, 'Bónuscred Sociedade de Crédito Direto S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),412, 'Banco Capital S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),422, 'Banco Safra S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),456, 'Banco MUFG Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),459, 'Banco Fit') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),464, 'Banco Sumitomo Mitsui Brasileiro S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),473, 'Banco Caixa Geral - Brasil S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),477, 'Citibank N.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),479, 'Banco ItaúBank 10  S.A.') ON CONFLICT DO NOTHING;`;
  await prisma.$executeRaw`INSERT INTO "Banks" (id, code, name) VALUES (gen_random_uuid(),495, 'Banco de La Provincia de Buenos Aires') ON CONFLICT DO NOTHING;`;
}
rawSql()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
